image:
        - Visual Studio 2017

clone_folder: c:\projects\source

install:
        - set QTDIR=C:\Qt\5.12.2\msvc2017
        - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
        - cmd: >-
                mkdir build

                cd build

                cmake c:\projects\source -G "Visual Studio 15"

                cmake --build . --config "Debug"

test_script:
        - cmd: ctest -C Debug

